### ISSUE TITLE
FileNotFoundException bei der Installition | Wait for answer -> Status: Answered

### ISSUE THREAD

**Issue by xPurplerain** [PlugDev-class/BusyCloud#1]
Leider ist beim Download der Proxy ein Fehler vorgefallen,
Entschuldigung meinerseits wenn ich daran was Falsch getan habe

Error Code meiner Konsole: https://just-paste.it/GYkz8ik6r8

**Comment by PlugDev-class** [comment]
Hey! Thank you for supporting and trying to change some things..
I visited your just-paste.it link and saw, that you're using some

**Comment by PlugDev-class** [comment]
Hey!

Thank you for reporting this error to me. I revisited the code and didn't find anything.
One of the main problems was: I recoded the half of my code, now it's very difficult to find the error.
But good news; Today I pushed the new version 1.03, so I recommend to download the latest build from my github.

If this doesn't help please contact me again. <3

Thank you!
